nelmio_cors:

    paths:
        '/api/login_check':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST' ]
            max_age: 3600
        '/api/.*':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'OPTIONS', 'GET', 'DELETE' ]
            max_age: 3600
