controllers:
    resource: ../src/Controller/
    type: attribute
kernel:
    resource: ../src/Kernel.php
    type: annotation
api_login_check:
    path: /api/login_check
    methods: POST
    defaults: { _controller: App\Controller\LoginController }
api_refresh_token:
    path: /api/token/refresh
    methods: POST
    defaults: { _controller: App\Controller\TokenController }
api_token_invalidate:
    path: /api/token/invalidate
    methods: POST
    defaults: { _controller: App\Controller\InactivateController }
app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
